version: '3.4'
services:
    # Descrevendo o serviço do banco de dados.
    banco:
        image: mysql:5.7
        container_name: banco
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: agenda
            MYSQL_DATABASE: agenda
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        volumes:
            - ./data:/var/lib/mysql
            - ./site/pessoa.sql:/docker-entrypoint-initdb.d/pessoa.sql
        networks: 
            - aplicacao-network
    web:
        image: nginx:latest
        container_name: aplicacao
        ports:
            - "8080:80"
        volumes:
            - ./site:/site
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks: 
            - aplicacao-network
    php:
        image: php-pdo-treinamento
        container_name: php
        volumes: 
            - ./site:/site
        networks: 
            - aplicacao-network
networks:
    aplicacao-network:
        driver: bridge