version: '3'
services:
    zabbix-appliance:
        image: zabbix/zabbix-appliance
        container_name: zabbix-appliance
        ports: 
            - 80:80
            - 10051:10051
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: agenda
            MYSQL_DATABASE: agenda
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword